/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IesCloud } from "./IesCloud";

export class IesCloudFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IesCloud {
    return new Contract(address, _abi, signerOrProvider) as IesCloud;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "Host_address",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "file",
        type: "bytes32",
      },
    ],
    name: "Dispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_buyer",
        type: "address",
      },
      {
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_distribute",
        type: "uint256",
      },
    ],
    name: "payRewards",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
