/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IesCloudInterface extends ethers.utils.Interface {
  functions: {
    "Dispute(address,bytes32)": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "payRewards(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "Dispute",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isAdmin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "payRewards",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "Dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payRewards", data: BytesLike): Result;

  events: {};
}

export class IesCloud extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IesCloudInterface;

  functions: {
    Dispute(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "Dispute(address,bytes32)"(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isAdmin(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isAdmin(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    payRewards(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "payRewards(address,address,uint256,uint256)"(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  Dispute(
    Host_address: string,
    file: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "Dispute(address,bytes32)"(
    Host_address: string,
    file: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isAdmin(user: string, overrides?: CallOverrides): Promise<boolean>;

  "isAdmin(address)"(user: string, overrides?: CallOverrides): Promise<boolean>;

  payRewards(
    _buyer: string,
    _seller: string,
    _value: BigNumberish,
    _distribute: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "payRewards(address,address,uint256,uint256)"(
    _buyer: string,
    _seller: string,
    _value: BigNumberish,
    _distribute: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    Dispute(
      Host_address: string,
      file: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "Dispute(address,bytes32)"(
      Host_address: string,
      file: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    isAdmin(user: string, overrides?: CallOverrides): Promise<boolean>;

    "isAdmin(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    payRewards(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "payRewards(address,address,uint256,uint256)"(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    Dispute(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "Dispute(address,bytes32)"(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isAdmin(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isAdmin(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payRewards(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "payRewards(address,address,uint256,uint256)"(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Dispute(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "Dispute(address,bytes32)"(
      Host_address: string,
      file: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isAdmin(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAdmin(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payRewards(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "payRewards(address,address,uint256,uint256)"(
      _buyer: string,
      _seller: string,
      _value: BigNumberish,
      _distribute: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
